# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrun < Formula
  desc "Secure environment variable runner — keep secrets out of project directories"
  homepage "https://github.com/MartSurv/secrun"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MartSurv/secrun/releases/download/v1.0.0/secrun_1.0.0_darwin_amd64.tar.gz"
      sha256 "62b8fee0a4ec93373d6402dd5566733d4b9765c5c561b00ff8c1edaf510d8a49"

      define_method(:install) do
        bin.install "secrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MartSurv/secrun/releases/download/v1.0.0/secrun_1.0.0_darwin_arm64.tar.gz"
      sha256 "7197594edbfaf9438e141c03e204ba41e369f566ede0e4e389c965f4954a847a"

      define_method(:install) do
        bin.install "secrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MartSurv/secrun/releases/download/v1.0.0/secrun_1.0.0_linux_amd64.tar.gz"
      sha256 "95f9d44b9982c017d9dc08e5ebbfc55caa0d1e2bf1046e6634ac535c868780ab"
      define_method(:install) do
        bin.install "secrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MartSurv/secrun/releases/download/v1.0.0/secrun_1.0.0_linux_arm64.tar.gz"
      sha256 "b427ad260132ce9f3c2670a8acb82331cecdd6c5610fe95d61a0f3ccfa3f2ff8"
      define_method(:install) do
        bin.install "secrun"
      end
    end
  end
end
